### ISSUE TITLE
error when checking deleted internal links

### ISSUE THREAD

**Issue by dwenzel** [sypets/brofix#231]
CLI-Command fails with 

```
Uncaught TYPO3 Exception Argument 1 passed to Sypets\Brofix\Linktype\ErrorParams::setErrorType() must be of the type string, int given, called in /var/www/html/app/web/typo3conf/ext/brofix/Classes/Linktype/InternalLinktype.php on line 201
thrown in file /var/www/html/app/web/typo3conf/ext/brofix/Classes/Linktype/ErrorParams.php
in line 105
```

**To Reproduce**
* create `tt_content` record with an internal link to a page and **delete** this page
* execute command `brofix:checklinks`

* **Expected behavior**
* command is executed without error **or**
* deleted records are ignored

**Screenshots**
`Sypets\Brofix\Linktype\InternalLinktype:`
![grafik](https://user-images.githubusercontent.com/712458/210396021-ec479219-6406-499a-933d-f8b228771064.png)
`$errorType` must be type `string` and is `int`

![grafik](https://user-images.githubusercontent.com/712458/210395818-e5c2b8f2-f180-4fac-8a68-fdc346c0906a.png)

**System (please complete the following information):**
 - TYPO3 version: 9.5
 - brofix version `1.0.6`
 - page_callouts version 1.0.4
 - installed with Composer

**Comment by sypets** [comment]
Resolved with #234
