### ISSUE TITLE
Make it possible to check pi_flexform fields as well

### ISSUE THREAD

**Issue by sypets** [sypets/brofix#248]
**Is your feature request related to a problem? Please describe.**

Broken links should be checked in pi_flexform fields as well if configured and these contain fields which may contain a link.

**Describe the solution you'd like**
Make it possible to check pi_flexform fields.

**Additional context**
Also check combination with other extensions, e.g. DCE

**Comment by begonagarea** [comment]
Do you have any plans to deal with this issue in the near future?

**Comment by sypets** [comment]
> Do you have any plans to deal with this issue in the near future?

I would like to deal with it but I have not made plans yet for the next steps. I will have a look now ...

(sorry about the late reply).

**Comment by sypets** [comment]
Known problem in combination with dce: 

* issue: https://github.com/a-r-m-i-n/dce/issues/102
* PR: https://github.com/a-r-m-i-n/dce/pull/103

There is currently an **experimental** PR #301 for TYPO3 v12 which works with dce if the PR is applied.
