### ISSUE TITLE
Broken links no longer displayed in RTE since v12

### ISSUE THREAD

**Issue by sypets** [sypets/brofix#282]
Since TYPO3 v12, the links are no longer marked as broken in RTE. 

This is a core problem and should be fixed in core: https://forge.typo3.org/issues/101357

This issue was created as placeholder.

**Comment by ToGetATockenOnly** [comment]
Cool, that you set up the issues yourself here publicly! I am running circles around EXT:brofix currently wondering to switch a major website to it from linkvalidator. Just today it came up again with non-admin rights access. Linkvalidator itself will go into its own module in v12 therefor. But there are other advantages with brofix .. primarily marking non-solvable error cases as such.

**Comment by sypets** [comment]
@ToGetATockenOnly Thank you for your encouraging and kind words.

Here in the issues section, I would like to keep it on topic, but you are welcome to contact me on TYPO3 Slack. There is also a channel for brofix / linkvalidator.

If you notice any other issues, please feel free to open issues. 

I have neglected both a bit these past weeks : I am currently working on a PR with some more cleanup in v12. I might come back to tackle this issue as well.

Unfortunatly, it is a bit much to work on both (linkvalidator and brofix), I used to also contribute to linkvalidator.

Long term I would like to have a common code base, obviously it has its drawbacks to split up the current workforce to work on 2 extensions.

**Comment by sypets** [comment]
btw, the problem described here was already resolved with patch https://review.typo3.org/c/Packages/TYPO3.CMS/+/80892 which was also backported to v12, so it should be fine.

Was merged / backported on September 7, 2023 and should be in latest v12 release **12.4.10**, see https://get.typo3.org/
