### ISSUE TITLE
Add new tab "Manage exclusions"

### ISSUE THREAD

**Issue by gaumondp** [sypets/brofix#95]
We can already manage the "exclusions" records stored in tx_brofix_exclude_link_target with the list module but it's not optimal. We want to add a new tab with those records with few functionnalities:

- [x] New tab "Manage exclusions"
- [x] List the exclusions based on "excludeLinkTarget.storagePid" (so the list isn't global for huge pagetrees)
- [x] Each line starts with a checkbox then the fileds: Linktarge(clickable), reason and hidden  (with sorting on each columns)
- [x] Before the list: Button for CSV export "Export exclusion list" (includes all columns of the table, not just those showned in the interface.
- [x] Button "Check all records"
- [x] Button "Delete all checked exclusions" (if all in a way it's a "reset" for the report)

We will provide a Pull Request for these new functions.

**Comment by sypets** [comment]
Thank you very much for your feature request. As we already talked about this, your suggestion and PR are welcome and I am looking forward to it. :thumbsup:

**Comment by sypets** [comment]
Is merged with #117 - thank you!
